### PR TITLE
prometheus: Add end point

### PR DESCRIPTION
**Pull request by odscjames**

### CODE REVIEW

**Comment by odscjames** [comment]
Q)

I'm not sure if calling get_data() each time is the correct thing to do - we do want to make sure that when /metrics is called the latest data is counted and not a stale copy, but I'm not sure if there is a better way to do that.

Q)

I had to update requirements.txt with a bit of tweaking by hand - https://github.com/ThreeSixtyGiving/covid19-tracker/issues/28 for more. I think this is correct - https://github.com/prometheus/client_python/blob/v0.12.0/setup.py has no other requirements.

Q)

This duplicates some of the logic from covidtracker/components/cards.py - I'm not sure if you would prefer that to be extracted into a common lib somewhere?

And note the extra install step now - if that password could be set to https://github.com/ThreeSixtyGiving/saltstack-deploy/blob/live/pillar/private/prometheus_pillar.sls#L2 please

**Comment by drkane** [comment]
Thanks James - I can take a look from a "does it break the tracker" perspective (can't imagine that it would), but I can't check whether it's giving you the right metrics for Prometheus.

> I'm not sure if calling get_data() each time is the correct thing to do - we do want to make sure that when /metrics is called the latest data is counted and not a stale copy, but I'm not sure if there is a better way to do that.

I think this is the right thing to do, it's what the tracker does on every request. The latest data is set up to fetch in the morning after the datastore has run, so there's potentially some conditions where it gets the previous days results and they're different to the datastore because the datastore has updated but the covid tracker hasn't yet.

>I had to update requirements.txt with a bit of tweaking by hand - #28 for more. I think this is correct - https://github.com/prometheus/client_python/blob/v0.12.0/setup.py has no other requirements.

I saw that - I did generate the requirements.txt on windows so I think that probably explains the issues you were getting. I haven't had any issues on the live version though, which is deployed on linux (although the requirements aren't compiled when its deployed).

> This duplicates some of the logic from covidtracker/components/cards.py - I'm not sure if you would prefer that to be extracted into a common lib somewhere?

I think it's sufficiently different that it's probably not worth the effort of extracting it

> And note the extra install step now - if that password could be set to https://github.com/ThreeSixtyGiving/saltstack-deploy/blob/live/pillar/private/prometheus_pillar.sls#L2 please

Presumably not putting the `PROMETHEUS_AUTH_USERNAME` in the readme is because the default one is fairly commonly used?

**Comment by odscjames** [comment]
> Thanks James - I can take a look from a "does it break the tracker" perspective (can't imagine that it would), but I can't check whether it's giving you the right metrics for Prometheus.

Thanks. 

> Presumably not putting the PROMETHEUS_AUTH_USERNAME in the readme is because the default one is fairly commonly used?

It's not about being common or not, the username can be anything we want. It's cos there's no reason to change it from the sensible default that is public in the code. (Where there **is** a reason to change the password from it's public default :smile: )

**Comment by drkane** [comment]
Awesome - I'm happy to merge this in in that case, it all works fine for me.

See also #30 where I've changed the code to allow for starting without the grants data being present.

**Comment by drkane** [comment]
NB I've given the Open Data Services Team access to this repo so you can make PRs directly if needed.

Not sure what the process is for getting the updates deployed to Mythic Beast? (I've made some other changes to the code as well).

**Pull request merged**
